image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build the client
        script:
        - cp Dockerrun.aws.client.json Dockerrun.aws.json
        - zip -r ravebox-client.zip Dockerrun.aws.json client
        - rm Dockerrun.aws.json
        artifacts:
        - ravebox-client.zip
    - step:
        name: Deploy the client to AWS
        caches:
          - pip
        script:
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.2
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: 'ap-southeast-2'
            APPLICATION_NAME: 'ravebox'
            ENVIRONMENT_NAME: 'ravebox-staging'
            ZIP_FILE: 'ravebox-client.zip'
            S3_BUCKET: 'ravebox-staging-deployment'
            VERSION_LABEL: 'ravebox-client-$BITBUCKET_BUILD_NUMBER'
            WAIT: 'true'
