image: atlassian/default-image:2

pipelines:
  tags:
    uat.*:
      - step:
          name: Package the files for the staging client
          script:
          - cp Dockerrun.aws.staging.client.json Dockerrun.aws.json
          - cp robots.staging.txt client/public/robots.txt
          - zip -r ravebox-client-$BITBUCKET_BUILD_NUMBER.zip Dockerrun.aws.json client
          - rm Dockerrun.aws.json
          - rm client/public/robots.txt
          artifacts:
          - ravebox-client-$BITBUCKET_BUILD_NUMBER.zip
      - step:
          name: Deploy the API to AWS
          caches:
            - pip
          script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              APPLICATION_NAME: 'ravebox'
              ENVIRONMENT_NAME: 'ravebox-staging'
              ZIP_FILE: 'ravebox-client-$BITBUCKET_BUILD_NUMBER.zip'
              S3_BUCKET: 'ravebox-staging-deployment'
              VERSION_LABEL: 'ravebox-client-$BITBUCKET_BUILD_NUMBER'
              WAIT: 'true'
